### ISSUE TITLE
HMR and server reload don't work

### ISSUE THREAD

**Issue by judgedim** [k911/swoole-bundle#187]
**Describe the bug**
The symfony project itself works fine and as expected. But the HRM doesn't work. I have to stop and start the swoole-server every time I change a file. Did I something wrong? The InotifyHRM class is loaded and initialized.

For my opinion problem here
https://github.com/k911/swoole-bundle/blob/develop/src/Server/Runtime/HMR/InotifyHMR.php#L78
because almost all files included (based on my investigation)

Function reload doesn't work too, so I have to do stop-start only.
It uses next code when I'm trying to reload it 
https://github.com/k911/swoole-bundle/blob/develop/src/Server/HttpServer.php#L98

I see next logs in var/log/swoole_dev.log
<p>
[2020-04-09 15:38:41 $4532.0]	INFO	Server is reloading all workers now
[2020-04-09 15:38:43 *4551.0]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
[2020-04-09 15:38:43 *4552.1]	WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
</p>

**Steps To Reproduce**
I created new empty project with only one controller. 

**Environment (please complete the following information):**
 - OS: Ubuntu
 - PHP Version: 
 - Swoole Version: 4.4.17
 - Symfony Version:5.0.7
 - Running in docker: No

**Comment by k911** [comment]
Unfortunately, I have to mark it as wontfix for now, because HMR will probably need some different approach (not only inotify but also fsevents), and probably it would be required to somehow rebuild Symfony DI container to make it work better. I've added this to the docs that HMR probably does not work with `running_mode: reactor`, I've tested it on Linux and it is working on Alpha feature basis (now also marked in Readme in #275 )
