### ISSUE TITLE
How to fix error handling?

### ISSUE THREAD

**Issue by enumag** [k911/swoole-bundle#20]
I tried to add this to my application. It seems to work fine while everything is running smoothly. The problem is that when a request causes an PHP error then the client never receives any kind of response - no error code 500, no debug information. The browser actually thinks the request did not finish even though it did.

Can you give me some advice how to handle this or at least where to look while trying to fix it? When I understand it I can help with writing some docs about it or maybe sending a PR if it is a small fix.

**Comment by k911** [comment]
In your `var/log/` directory you should have logs containing error information.

I think your issue will be uncaught error, which then breaks swoole server worker. To handle errors correctly you can use `twig` with it's debug handler, or write custom one. 
https://symfony.com/doc/current/controller/error_pages.html

I agree, we could provide something like "UncaughtExceptionRequestHandler" which would catch all uncaught exceptions and provide useful information, in case error is not handled properly.

That would require to create class that implements https://github.com/k911/swoole-bundle/blob/develop/src/Server/RequestHandler/RequestHandlerInterface.php

for example:

```php
namespace K911\Swoole\Server\RequestHandler;

final class UncaughtExceptionRequestHandler implements RequestHandlerInterface {

    private $decorated;

    public function  __construct(RequestHandlerInterface $decorated) {
       $this->decorated = $decorated;
    }

    /**
    * {@inheritdoc}
    */
    public function handle(Request $request, Response $response): void {
        try {
            $this->decorated->handle($request, $response);
        } catch (ThrowableInterface $exception) {
            $response->end('error');
        }
    }
}
```

**Comment by enumag** [comment]
Thanks, I'll see what I can do with this advice. I'm not sure if I can find the time this week so maybe next monday.

In my case I don't need to use twig for the error page since I'm building an API anyway.

**Comment by enumag** [comment]
Btw these request handlers seem very similar to PSR-15 middlewares. Why aren't we using those instead?

**Comment by k911** [comment]
@enumag Yeah, it would be very nice to stick with PSR, but I think it would require at least that Swoole Request/Response objects implements PSR-7 themselves, although it may be not so easy to implement PHP interface in PHP extension written in C. See https://github.com/swoole/swoole-src/issues/559

I also thought about creating PSR-7 adpaters, but I decided not to, because it would affect complexity and performance, and probably codebase as it would be a nightmare to support. Right now it is needed to transform to Symfony\Request Swoole\Response anyway.

Also, there are some architectural differences between PSR and how swoole operates. Swoole\Response object is instantiated by server, not end user, and PSR-15 assumes that Middleware/RequestHandler will return newly created Response object, which is not possible with swoole AFAIK.

See https://github.com/swoole/swoole-docs/blob/master/modules/swoole-http-server/method/swoole-http-server/on.md#example and https://github.com/swoole/swoole-docs/blob/master/modules/swoole-http-server/method/swoole-http-response/end.md

Regarding API case: That's a valid point, `twig` should be unecessary, instead we could return response in  that new RequestHandler for example in ` application/problem+json` format, enabled by default in debug/dev environment.

Thanks for your feedback!

**Comment by enumag** [comment]
Hmm I'm not sure what was wrong. Error handling seems to work fine now. I'll reopen this and investigate if I run into the problem again.

**Comment by domgraziano** [comment]
I'm experiencing this too. 
I can confirm looking at the log that error seems to be caused by the symfony error handling that can't catch  `Swoole\ExitException` 
this is reproducible by just throwing a new Exception or Error from a symfony controller`
```
Fatal error: Uncaught Swoole\ExitException: swoole exit in /var/www/vendor/symfony/debug/ErrorHandler.php:668
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler::Symfony\Component\Debug\{closure}()
#1 {main}
  thrown in /var/www/vendor/symfony/debug/ErrorHandler.php on line 668
```

**Comment by k911** [comment]
@domgraziano Please open new issue and provide swoole logs and symfony logs or maybe even a small reproducer repository

**Comment by domgraziano** [comment]
@k911 sure done at #78
