### ISSUE TITLE
Fallback to Symfony error handler on error or exception

### ISSUE THREAD

**Issue by Rastusik** [k911/swoole-bundle#227]
**Is your feature request related to a problem? Please describe.**
Current ProductionExceptionHandler is too simple. It would be better if the bundle exception handler would be able to work with Symfony exception/error handler to display messages in Symfony style.

**Describe the solution you'd like**
I would like to modify the ProductionExceptionHandler to use the Symfony error/exception handlers.

**Describe alternatives you've considered**
I haven't considered other alternatives, since I already have a working implementation

**Additional context**
The point is to be able to have Symfony error messages in DEV environment and a generic error message (preferably from Symfony) in PROD.

**Comment by k911** [comment]
Like outlined in issues connected to this pull request, default production error handler has been explicitly added in PR https://github.com/k911/swoole-bundle/pull/79 due to the bug, when not catching errors would result in timeout. IMO error handling should not be part of this bundle, or at least it should be optional, as it is currently. So the only option that seems reasonable is to create a new (optional) error handler which will be able to handle more complex scenarios.
