### ISSUE TITLE
Different Voter Result

### ISSUE THREAD

**Issue by surya4crowde** [k911/swoole-bundle#489]
**Describe the bug**
Different Voter Result Between Conventional, Road Runner and Swoole Bundle

**Steps To Reproduce**
I use this repo https://github.com/KejawenLab/SemartApiSkeleton (using docker) and add swoole bundle, and i dont add any configuration, just default and then run the aplication using swoole server

**Expected behavior**
The Voter return GRANTED

Result in Nginx and Roud Runner Bundle
![Screenshot from 2021-03-25 22-05-49](https://user-images.githubusercontent.com/70564773/113268577-b96b4f00-9301-11eb-9d8e-a802abd8f863.png)

Result in Swoole Bundle
![Screenshot from 2021-04-01 15-32-49](https://user-images.githubusercontent.com/70564773/113268660-d011a600-9301-11eb-8d80-eb28d77c39e3.png)

![Screenshot from 2021-04-01 15-34-22](https://user-images.githubusercontent.com/70564773/113268702-dc95fe80-9301-11eb-871a-9f984226be12.png)

The authenticator is returned User Entity as Espected and the ROLE_USER is setted but in Swoole, the Voter returned DENIED

**Comment by k911** [comment]
My guess it's due to session usage, and if that's true it makes it not bug.

Try enabling session and then check whether it's working: https://github.com/k911/swoole-bundle/blob/develop/tests/Fixtures/Symfony/app/config/session/swoole.yaml 

if it's still not working we'll need more details to debug issue, preferably logs, small repository with reproduction of this bug, hints where do you think the failure may be in codebase or most preferably MR with bugfix.

**Comment by surya4crowde** [comment]
Hi @k911 thank you for your reply, basically i use redis storage for session (snc redis bundle) for session and enable by default

`swoole:
    http_server:
        services:
            session_cookie_event_listener: true`
            
I just add that lines and working perfectly, thank you very much

May you need to add this config in documentation or provide symfony recipes to handle it.... Thank you so much, your bundle is awesome
